export interface ChunkStrategyOption {
  value: string
  label: string
  description: string
  icon: 'recursive' | 'token' | 'sentence' | 'hierarchical' | 'integrated' | 'separator'
  badge?: string
  group?: 'preset' | 'langchain' | 'llama_index' | 'integrated'
  disabled?: boolean
}

export const CHUNK_STRATEGY_OPTIONS: ChunkStrategyOption[] = [
  // Presets
  {
    value: 'auto',
    label: '自动选择（推荐）',
    description:
      '自动识别内容形态（Q&A/对话/论文/大纲/Markdown/JSON），选择合适的切块器。',
    icon: 'recursive',
    badge: '推荐',
    group: 'preset',
  },
  {
    value: 'pdf_layout',
    label: 'PDF 版式感知（bbox/columns）',
    description:
      '适用于包含 @@page\\tl\\tr\\tt\\tb## 位置标签的 PDF 解析结果：按版面块聚合，写入 bbox/column 元数据，并从 chunk 文本中去除位置标签。',
    icon: 'hierarchical',
    badge: 'PDF',
    group: 'preset',
  },
  {
    value: 'manuscript',
    label: '文稿/讲稿（预设）',
    description:
      '面向文稿/讲稿/手稿/报告：优先按 Q&A / 对话 / 论文 / 大纲切块。',
    icon: 'hierarchical',
    badge: '文稿',
    group: 'preset',
  },
  {
    value: 'outline',
    label: '大纲/章节（预设）',
    description: '识别 1. / 1.1 / 第X章 等编号标题，按章节结构切块。',
    icon: 'hierarchical',
    badge: '大纲',
    group: 'preset',
  },
  {
    value: 'transcript',
    label: '访谈/会议纪要（预设）',
    description: '识别“张三：…”等说话人行，尽量保持完整发言轮次。',
    icon: 'sentence',
    badge: '对话',
    group: 'preset',
  },
  {
    value: 'qa_pairs',
    label: 'FAQ / Q&A（预设）',
    description: '识别 Q/A 或 问/答 标记，尽量保持每组问答不被拆散。',
    icon: 'sentence',
    badge: 'Q&A',
    group: 'preset',
  },
  {
    value: 'paper',
    label: '论文/报告（预设）',
    description: '识别摘要/引言/方法/结果/讨论/参考文献等常见章节并切块。',
    icon: 'hierarchical',
    badge: '论文',
    group: 'preset',
  },
  {
    value: 'book_structured',
    label: '书籍/长文档（预设）',
    description: '识别 Chapter/Part/Volume/第X章 等结构，按章节上下文切块。',
    icon: 'hierarchical',
    badge: '书籍',
    group: 'preset',
  },
  {
    value: 'laws_structured',
    label: '法律/合同/制度（预设）',
    description: '识别 第X条/（一）/Article 等条款结构，按条款切块。',
    icon: 'hierarchical',
    badge: '条款',
    group: 'preset',
  },
  {
    value: 'email_thread',
    label: '邮件线程（预设）',
    description: '识别 From/To/Subject/-----Original Message----- 等，按邮件消息切块。',
    icon: 'sentence',
    badge: '邮件',
    group: 'preset',
  },
  {
    value: 'sop_steps',
    label: 'SOP/操作步骤（预设）',
    description: '识别 Step 1/步骤一 等步骤标题，尽量保持步骤不被拆散。',
    icon: 'hierarchical',
    badge: 'SOP',
    group: 'preset',
  },
  {
    value: 'glossary',
    label: '术语表/词典（预设）',
    description: '识别“术语：定义”条目，按条目切块并保留术语列表。',
    icon: 'separator',
    badge: '术语',
    group: 'preset',
  },
  {
    value: 'resume_structured',
    label: '简历/履历（预设）',
    description: '识别教育/经历/项目/技能等常见章节，按简历结构切块。',
    icon: 'hierarchical',
    badge: '简历',
    group: 'preset',
  },
  {
    value: 'presentation_slides',
    label: 'PPT/幻灯片（预设）',
    description: "识别 --- 分隔或 Slide/Page 标记，尽量保持每页/每张幻灯片内容完整。",
    icon: 'hierarchical',
    badge: 'PPT',
    group: 'preset',
  },
  {
    value: 'chat_history',
    label: '聊天记录（预设）',
    description: '识别带时间戳的对话记录，按消息分组并保留上下文。',
    icon: 'sentence',
    badge: '聊天',
    group: 'preset',
  },
  {
    value: 'markdown_table',
    label: 'Markdown 表格（预设）',
    description: '识别 Markdown 表格块，避免在行内切分，超大表格按行边界拆分。',
    icon: 'separator',
    badge: '表格',
    group: 'preset',
  },
  {
    value: 'csv_rows',
    label: 'CSV 行（预设）',
    description: "适配 CsvParser 的 row N: 输出，按行聚合切块并支持行级 overlap。",
    icon: 'separator',
    badge: 'CSV',
    group: 'preset',
  },
  {
    value: 'spreadsheet_sheet',
    label: 'Excel 工作表（预设）',
    description: "适配 ExcelParser 的 ## Sheet: 输出，先按工作表切分再切块。",
    icon: 'hierarchical',
    badge: '工作表',
    group: 'preset',
  },
  {
    value: 'changelog',
    label: 'Changelog / Release Notes（预设）',
    description: '识别版本/Unreleased 标题，按发布版本切块。',
    icon: 'hierarchical',
    badge: 'Changelog',
    group: 'preset',
  },
  {
    value: 'log_events',
    label: '日志（预设）',
    description: '识别时间戳+级别的日志行，按日志条目聚合切块。',
    icon: 'separator',
    badge: 'Log',
    group: 'preset',
  },
  {
    value: 'subtitles',
    label: '字幕 SRT/VTT（预设）',
    description: '识别 00:00:00,000 --> 00:00:01,000 时间码，按字幕 cue 切块。',
    icon: 'sentence',
    badge: '字幕',
    group: 'preset',
  },
  {
    value: 'api_reference',
    label: 'API 接口文档（预设）',
    description: '识别 GET /path 等端点签名，按接口块切块。',
    icon: 'hierarchical',
    badge: 'API',
    group: 'preset',
  },
  {
    value: 'diff_patch',
    label: 'Diff / Patch（预设）',
    description: '识别 diff --git 与 @@ hunk，按文件与 hunk 边界切块。',
    icon: 'separator',
    badge: 'Diff',
    group: 'preset',
  },
  {
    value: 'kv_config',
    label: '配置 Key=Value（预设）',
    description: '识别大量 KEY=VALUE（支持 [section]），按配置项聚合切块。',
    icon: 'separator',
    badge: '配置',
    group: 'preset',
  },
  {
    value: 'qa_markdown',
    label: 'Markdown Q&A（预设）',
    description: '识别 **Q:**/**A:** 或 ### Q: 等 Markdown 形式问答，按问答对切块。',
    icon: 'sentence',
    badge: 'Q&A',
    group: 'preset',
  },
  {
    value: 'meeting_minutes',
    label: '会议纪要/行动项（预设）',
    description: '识别 议程/讨论/决议/行动项 等章节，按纪要结构切块。',
    icon: 'hierarchical',
    badge: '纪要',
    group: 'preset',
  },
  {
    value: 'timeline_events',
    label: '时间线/事件（预设）',
    description: '识别以日期开头的事件行（YYYY-MM-DD），按事件聚合切块。',
    icon: 'hierarchical',
    badge: '时间线',
    group: 'preset',
  },
  {
    value: 'yaml_manifest',
    label: 'YAML / K8s Manifest（预设）',
    description: "识别 YAML 多文档（---）与 kind/name，按文档聚合切块。",
    icon: 'hierarchical',
    badge: 'YAML',
    group: 'preset',
  },
  {
    value: 'toml_config',
    label: 'TOML 配置（预设）',
    description: '识别 [table] / [[array]] 与 key=value，按表/配置项聚合切块。',
    icon: 'separator',
    badge: 'TOML',
    group: 'preset',
  },
  {
    value: 'sql_schema',
    label: 'SQL Schema / DDL（预设）',
    description: '识别 CREATE/ALTER 等语句，按表/对象语句块切块。',
    icon: 'separator',
    badge: 'SQL',
    group: 'preset',
  },
  {
    value: 'stacktrace',
    label: '异常堆栈/Traceback（预设）',
    description: '识别 Python/Java 等堆栈块，尽量保持完整 traceback 不拆散。',
    icon: 'separator',
    badge: 'Trace',
    group: 'preset',
  },
  {
    value: 'git_commit_log',
    label: 'Git Commit Log（预设）',
    description: "识别 commit <sha> / Author / Date 等提交头，按提交块切块并保留提交上下文。",
    icon: 'separator',
    badge: 'Git',
    group: 'preset',
  },
  {
    value: 'jsonl_records',
    label: 'JSONL / NDJSON（预设）',
    description: '按每行 JSON 记录聚合切块，避免把记录拆散（适合日志/事件流）。',
    icon: 'separator',
    badge: 'JSONL',
    group: 'preset',
  },
  {
    value: 'xml_feed',
    label: 'RSS / Atom Feed（预设）',
    description: '识别 <item>/<entry> 条目块，按条目切块并保留标题等元信息。',
    icon: 'hierarchical',
    badge: 'Feed',
    group: 'preset',
  },
  {
    value: 'openapi_spec',
    label: 'OpenAPI / Swagger（预设）',
    description: '识别 paths: 下的端点块，按 path 切块，避免接口说明被拆散。',
    icon: 'hierarchical',
    badge: 'OpenAPI',
    group: 'preset',
  },
  {
    value: 'graphql_schema',
    label: 'GraphQL Schema（预设）',
    description: '按 type/input/enum/interface/union 等顶层定义切块，保持 schema 结构。',
    icon: 'separator',
    badge: 'GraphQL',
    group: 'preset',
  },
  {
    value: 'proto_schema',
    label: 'Protobuf / .proto（预设）',
    description: '按 message/enum/service 等顶层块切块（brace-aware），适合接口与数据结构定义。',
    icon: 'separator',
    badge: 'Proto',
    group: 'preset',
  },
  {
    value: 'terraform_hcl',
    label: 'Terraform / HCL（预设）',
    description: '按 resource/module/variable 等块切块（brace-aware），保持配置块完整。',
    icon: 'separator',
    badge: 'Terraform',
    group: 'preset',
  },
  {
    value: 'postmortem_report',
    label: '事故复盘 / RCA（预设）',
    description: '识别 Summary/Impact/Timeline/Root Cause/Action Items 等章节，按复盘结构切块。',
    icon: 'hierarchical',
    badge: 'RCA',
    group: 'preset',
  },
  {
    value: 'docker_compose',
    label: 'Docker Compose（预设）',
    description: '识别 services: 下的服务块，按 service 切块，适合 docker-compose.yml。',
    icon: 'hierarchical',
    badge: 'Compose',
    group: 'preset',
  },
  {
    value: 'github_actions',
    label: 'GitHub Actions（预设）',
    description: '识别 jobs: 下的 job 块，按 job 切块，适合 .github/workflows/*.yml。',
    icon: 'hierarchical',
    badge: 'Actions',
    group: 'preset',
  },
  {
    value: 'gitlab_ci',
    label: 'GitLab CI（预设）',
    description: '按顶层 job/config 块切块（stages/variables/job 等），适合 .gitlab-ci.yml。',
    icon: 'hierarchical',
    badge: 'CI',
    group: 'preset',
  },
  {
    value: 'ansible_playbook',
    label: 'Ansible Playbook（预设）',
    description: '识别顶层 play（- name/- hosts），按 play 块切块，适合 playbook.yml。',
    icon: 'hierarchical',
    badge: 'Ansible',
    group: 'preset',
  },
  {
    value: 'markdown_frontmatter',
    label: 'Markdown Frontmatter（预设）',
    description: '保留 YAML Frontmatter（--- ... ---），再对正文按 Markdown 友好分隔切块。',
    icon: 'hierarchical',
    badge: 'FM',
    group: 'preset',
  },
  {
    value: 'http_trace',
    label: 'HTTP Trace（预设）',
    description: '识别 GET/POST ... HTTP/1.1 与 HTTP/1.1 200 等请求响应头，按请求块切块。',
    icon: 'separator',
    badge: 'HTTP',
    group: 'preset',
  },
  {
    value: 'junit_xml',
    label: 'JUnit XML（预设）',
    description: '识别 <testsuite>/<testcase>，按 testcase 块切块，适合测试报告 XML。',
    icon: 'hierarchical',
    badge: 'JUnit',
    group: 'preset',
  },
  {
    value: 'sitemap_xml',
    label: 'Sitemap XML（预设）',
    description: '识别 <urlset>/<sitemapindex> 中的条目，按 <url>/<sitemap> 块切块。',
    icon: 'hierarchical',
    badge: 'Sitemap',
    group: 'preset',
  },
  {
    value: 'maven_pom',
    label: 'Maven POM（预设）',
    description: '识别 pom.xml 中的 <dependency>/<plugin>，按记录聚合切块并提取坐标信息。',
    icon: 'separator',
    badge: 'Maven',
    group: 'preset',
  },
  {
    value: 'terraform_plan',
    label: 'Terraform Plan（预设）',
    description: '识别 “# ... will be ...” 变更头，按资源变更块切块，适合 terraform plan 输出。',
    icon: 'separator',
    badge: 'TF Plan',
    group: 'preset',
  },
  {
    value: 'dockerfile',
    label: 'Dockerfile（预设）',
    description: '识别 FROM 阶段与 RUN/COPY 等指令块，按阶段/指令聚合切块。',
    icon: 'separator',
    badge: 'Docker',
    group: 'preset',
  },
  {
    value: 'makefile',
    label: 'Makefile（预设）',
    description: '识别 target: 规则与配方（tab 缩进），按 target 块聚合切块。',
    icon: 'separator',
    badge: 'Make',
    group: 'preset',
  },
  {
    value: 'nginx_config',
    label: 'Nginx 配置（预设）',
    description: '识别 server {}/location {} 等块，按 server 块聚合切块。',
    icon: 'separator',
    badge: 'Nginx',
    group: 'preset',
  },
  {
    value: 'jira_ticket',
    label: 'Jira / 工单（预设）',
    description: '识别 Summary/Description/Steps/Expected/Actual 等字段，按工单结构切块。',
    icon: 'hierarchical',
    badge: 'Jira',
    group: 'preset',
  },
  {
    value: 'prd_spec',
    label: 'PRD / 需求文档（预设）',
    description: '识别 背景/目标/范围/需求/验收/风险/里程碑 等章节，按 PRD 结构切块。',
    icon: 'hierarchical',
    badge: 'PRD',
    group: 'preset',
  },
  {
    value: 'html_sections',
    label: 'HTML 标题（预设）',
    description: '识别 <h1>-<h6> 标题标签，按标题层级切块。',
    icon: 'hierarchical',
    badge: 'HTML',
    group: 'preset',
  },
  {
    value: 'rst_sections',
    label: 'reStructuredText（预设）',
    description: '识别 ===/--- 下划线标题，按章节结构切块。',
    icon: 'hierarchical',
    badge: 'RST',
    group: 'preset',
  },
  {
    value: 'asciidoc_sections',
    label: 'AsciiDoc（预设）',
    description: '识别 =/==/=== 标题行，按章节层级切块。',
    icon: 'hierarchical',
    badge: 'AsciiDoc',
    group: 'preset',
  },
  {
    value: 'latex_sections',
    label: 'LaTeX（预设）',
    description: '识别 \\section/\\chapter 等结构命令，按章节切块。',
    icon: 'hierarchical',
    badge: 'LaTeX',
    group: 'preset',
  },
  {
    value: 'orgmode_sections',
    label: 'Org-mode（预设）',
    description: '识别 * / ** 标题行，按章节层级切块。',
    icon: 'hierarchical',
    badge: 'Org',
    group: 'preset',
  },
  {
    value: 'mediawiki_sections',
    label: 'WikiText / MediaWiki（预设）',
    description: '识别 == Heading == 标题行，按章节层级切块。',
    icon: 'hierarchical',
    badge: 'Wiki',
    group: 'preset',
  },

  // LangChain / local strategies
  {
    value: 'langchain_recursive',
    label: 'LangChain 递归切分',
    description: '按分隔符（段落、句号等）递归切分，保留语义完整性。',
    icon: 'recursive',
    badge: '通用',
    group: 'langchain',
  },
  {
    value: 'semantic_sentence',
    label: '语义句子切分',
    description: '按句子边界聚合，减少断句（适合长文本）。',
    icon: 'sentence',
    badge: '句子',
    group: 'langchain',
  },
  {
    value: 'sentence_window',
    label: '句子窗口切分',
    description: '按句子窗口聚合，使用“按句子”重叠（避免 overlap 截断句子）。',
    icon: 'sentence',
    badge: '窗口',
    group: 'langchain',
  },
  {
    value: 'parent_child',
    label: '父子切分',
    description: '先生成父块，再切子块，保留 parent_id。',
    icon: 'hierarchical',
    badge: '层级',
    group: 'langchain',
  },
  {
    value: 'langchain_token',
    label: 'LangChain Token 切分',
    description: '按 Token 数量切分，适合控制 LLM 输入长度。',
    icon: 'token',
    badge: 'Token',
    group: 'langchain',
  },
  {
    value: 'separator',
    label: '自定义分隔符切分',
    description: '按指定分隔符直接切分，适合结构化/规则化文档。',
    icon: 'separator',
    badge: '自定义',
    group: 'langchain',
  },
  {
    value: 'markdown_header',
    label: 'Markdown 标题切分',
    description: '按 # / ## / ### 标题层级切分，保留标题上下文。',
    icon: 'hierarchical',
    badge: 'Markdown',
    group: 'langchain',
  },
  {
    value: 'markdown_outline',
    label: 'Markdown Outline Split',
    description: 'Split by markdown heading hierarchy and preserve outline_path/header_path.',
    icon: 'hierarchical',
    badge: 'Markdown',
    group: 'langchain',
  },
  {
    value: 'markdown_aware',
    label: 'Markdown 感知切分',
    description: '针对 Markdown 结构优化（标题/列表/代码块）并保留字符位置。',
    icon: 'recursive',
    badge: 'Markdown',
    group: 'langchain',
  },
  {
    value: 'json',
    label: 'JSON 结构切分',
    description: '尽量按 JSON 结构拆分（数组元素/对象键），通常不使用 overlap。',
    icon: 'separator',
    badge: 'JSON',
    group: 'langchain',
  },
  {
    value: 'code',
    label: '代码切分',
    description: '按代码结构/语句块切分（适合多语言代码）。',
    icon: 'separator',
    badge: 'Code',
    group: 'langchain',
  },
  {
    value: 'smart_code',
    label: '智能代码切分（Python）',
    description: '基于 AST-like 结构切分 Python，减少函数/类被拆分。',
    icon: 'separator',
    badge: 'Python',
    group: 'langchain',
  },

  // LlamaIndex
  {
    value: 'llama_index',
    label: 'LlamaIndex 句子切分',
    description: '基于句子边界的智能切分，保持语义完整性。',
    icon: 'sentence',
    badge: 'LlamaIndex',
    group: 'llama_index',
  },
  {
    value: 'llama_index_hierarchical',
    label: 'LlamaIndex 分层切分',
    description: '多层级切分策略，适合复杂文档结构。',
    icon: 'hierarchical',
    badge: '分层',
    group: 'llama_index',
  },

  // Integrated pipeline (parse + chunk integrated)
  {
    value: 'integrated_naive',
    label: 'Integrated pipeline 通用切分',
    description: 'Integrated pipeline 通用文档切分（集成解析+切块）。',
    icon: 'integrated',
    badge: 'Integrated pipeline',
    group: 'integrated',
  },
  {
    value: 'integrated_book',
    label: 'Integrated pipeline 书籍切分',
    description: '针对书籍/长文档优化，尽量保留章节结构。',
    icon: 'integrated',
    badge: '书籍',
    group: 'integrated',
  },
  {
    value: 'integrated_laws',
    label: 'Integrated pipeline 法律切分',
    description: '针对法律文档优化，尽量保留条款结构。',
    icon: 'integrated',
    badge: '法律',
    group: 'integrated',
  },
  {
    value: 'integrated_email',
    label: 'Integrated pipeline 邮件切分',
    description: '针对邮件/通信优化，尽量保留引用结构。',
    icon: 'integrated',
    badge: '邮件',
    group: 'integrated',
  },
]

export function getChunkStrategyOption(value?: string) {
  const normalized = (value || '').toLowerCase()
  return (
    CHUNK_STRATEGY_OPTIONS.find((option) => option.value === normalized) ||
    CHUNK_STRATEGY_OPTIONS.find((option) => option.value === 'langchain_recursive') ||
    CHUNK_STRATEGY_OPTIONS[0]
  )
}

export function getChunkStrategyLabel(value?: string) {
  return getChunkStrategyOption(value).label
}

export function getStrategiesByGroup(group: string) {
  return CHUNK_STRATEGY_OPTIONS.filter((option) => option.group === group)
}

export const INGESTION_FALLBACK_CHUNK_STRATEGY_VALUES = [
  'langchain_recursive',
  ...getStrategiesByGroup('integrated').map((option) => option.value),
]
