repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=10240"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: web-ui-check
        name: web-ui-check
        entry: pnpm -C web run ui-check
        language: system
        pass_filenames: false
        files: ^web/
