import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

describe('pdf preview source', () => {
  it('moves PDF highlight preprocessing into a worker-backed computation pipeline', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'pdf-preview.tsx'), 'utf8')

    expect(src).toContain("useTranslations('ChunkPreview')")
    expect(src).toContain("t('pdfPreview.loading.message')")
    expect(src).toContain("t('pdfPreview.loading.srMessage')")
    expect(src).toContain("t('pdfPreview.errors.preparationFailedTitle')")
    expect(src).toContain("t('pdfPreview.errors.preparationFailedDescription')")
    expect(src).toContain("t('pdfPreview.states.notPdf')")
    expect(src).toContain("t('pdfPreview.states.noFile')")
    expect(src).toContain("t('pdfPreview.states.cannotRenderTitle')")
    expect(src).toContain("t('pdfPreview.states.originalTextMissing')")
    expect(src).toContain("t('pdfPreview.states.includeOriginalTextDisabled')")
    expect(src).toContain("t('pdfPreview.states.noPositionTagsTitle')")
    expect(src).toContain("t('pdfPreview.states.noPositionTagsDescription')")
    expect(src).toContain("t('pdfPreview.actions.showAllBoxes')")
    expect(src).toContain("t('pdfPreview.actions.highlightOnly')")
    expect(src).toContain('PdfPreviewLoadingSkeleton')
    expect(src).toContain('PageLoading')
    expect(src).toContain("new URL('../../../../../workers/pdf-preview.worker.ts', import.meta.url)")
    expect(src).toContain('wrap<PdfPreviewWorkerApi>')
    expect(src).toContain('computePdfPreviewData')
    expect(src).toContain('chunkBlockIdsByIndexEntries')
    expect(src).toContain('const blockIdsByChunkIndex = useMemo(')
    expect(src).toContain('blockIdsByChunkIndex.get(selectedChunkIndex) || []')
    expect(src).toContain('blockIdsByChunkIndex.get(hoveredChunkIndex) || []')
    expect(src).toContain('blockIdToPageIndexEntries')
    expect(src).toContain('const blockIdToPageIndex = useMemo(')
    expect(src).toContain('blockIdToPageIndex={blockIdToPageIndex}')
    expect(src).toContain('boxesByPageEntries')
    expect(src).toContain('const boxesByPage = useMemo(')
    expect(src).toContain('boxesByPage={boxesByPage}')
    expect(src).toContain('pdfPreviewWorkerRef.current?.terminate()')
    expect(src).not.toContain('blocks={blocksWithPositions}')
    expect(src).not.toContain('findBlockIdsForChunkIndex({')
    expect(src).not.toContain('const parsed = useMemo(() =>')
    expect(src).not.toContain('extractBlocksFromMarkdownWithRanges(rawOriginal)')
    expect(src).not.toContain('createPositionTagIndexMapper(rawOriginal')
    expect(src).not.toContain('buildBlockIdToBestChunkIndex(blockRanges, chunkRanges)')
  })
})
