import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: 'guide'}],
  backend: [{type: 'autogenerated', dirName: 'backend'}],
  frontend: [{type: 'autogenerated', dirName: 'frontend'}],
  integration: [{type: 'autogenerated', dirName: 'integration'}],
  ops: [{type: 'autogenerated', dirName: 'ops'}],
};

export default sidebars;
