import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

describe('document viewer panel source', () => {
  it('extracts shell and state wiring while preserving document viewer modules', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'document-viewer-panel.tsx'), 'utf8')
    const shellSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/document-viewer-panel-shell.tsx'), 'utf8')
    const hookSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/use-document-viewer-panel-state.ts'), 'utf8')
    const chunksTabSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/chunks-tab-panel.tsx'), 'utf8')

    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/chunk-renderer.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/highlight-layer.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/floating-menu.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/chunk-editor-dialog.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/qa-generation-dialog.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/preview-tab-panel.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/text-tab-panel.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/chunks-toolbar-panel.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/document-viewer-header.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/chunks-tab-panel.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/document-viewer-panel-shell.tsx'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/use-document-viewer-panel-state.ts'))).toBe(true)
    expect(fs.existsSync(path.resolve(__dirname, 'document-viewer/document-viewer-panel-utils.ts'))).toBe(true)
    expect(chunksTabSrc).toContain('DocumentChunkCard')
    expect(src).toContain('useDocumentViewerPanelState')
    expect(src).toContain('DocumentViewerPanelShell')
    expect(src).not.toContain('FloatingMenu')
    expect(src).not.toContain('ChunkEditorDialog')
    expect(src).not.toContain('QAGenerationDialog')
    expect(src).not.toContain('PreviewTabPanel')
    expect(src).not.toContain('TextTabPanel')
    expect(src).not.toContain('DocumentViewerHeader')
    expect(src).not.toContain('ChunksTabPanel')
    expect(src).not.toContain('document.execCommand(')
    expect(src).not.toContain('removeChild(')
    expect(src).not.toContain('searchParams.set("token"')
    expect(src).not.toContain("searchParams.set('token'")
    expect(shellSrc).toContain('FloatingMenu')
    expect(shellSrc).toContain('ChunkEditorDialog')
    expect(shellSrc).toContain('QAGenerationDialog')
    expect(shellSrc).toContain('PreviewTabPanel')
    expect(shellSrc).toContain('TextTabPanel')
    expect(shellSrc).toContain('DocumentViewerHeader')
    expect(shellSrc).toContain('ChunksTabPanel')
    expect(shellSrc).toContain('bg-sidebar/90')
    expect(shellSrc).toContain('border-sidebar-border/70')
    expect(shellSrc).toContain('backdrop-blur-xl')
    expect(shellSrc).toContain('chunkEditorStartChar')
    expect(shellSrc).toContain('chunkEditorEndChar')
    expect(shellSrc).toContain('canRerunRetrieve')
    expect(shellSrc).toContain('text-[11px] font-semibold tracking-[0.14em]')
    expect(hookSrc).toContain("getPrefetchedDocument")
    expect(hookSrc).toContain("getPrefetchedChunk")
    expect(hookSrc).toContain('setHighlightChunkState((prev) => (prev?.id === updated.id ? updated : prev))')
    expect(hookSrc).toContain('export function useDocumentViewerPanelState()')
    expect(hookSrc).toContain('const runRetrievePreview = React.useCallback(async () =>')
    expect(hookSrc).toContain('chunkEditorStartChar')
    expect(hookSrc).toContain('chunkEditorEndChar')
    expect(hookSrc).toContain('"save_reembed"')
    expect(hookSrc).toContain('"save_rerun"')
  })

  it('exposes the opened document filename as a heading for live deep-link smoke checks', () => {
    const headerSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/document-viewer-header.tsx'), 'utf8')

    expect(headerSrc).toContain('<h2')
    expect(headerSrc).toContain('{filename || "加载中..."}')
  })

  it('keeps document preview scrolling inside the viewer so citation jumps do not move the tab bar offscreen', () => {
    const shellSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/document-viewer-panel-shell.tsx'), 'utf8')

    expect(shellSrc).toContain('className="flex min-h-0 flex-1 flex-col"')
    expect(shellSrc).toContain('className="relative m-0 min-h-0 flex-1 overflow-hidden bg-muted/30 dark:bg-muted/20"')
    expect(shellSrc).toContain('className="m-0 min-h-0 flex-1 overflow-hidden"')
  })

  it('supports dragging the viewer side rail to resize the document panel', () => {
    const shellSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/document-viewer-panel-shell.tsx'), 'utf8')
    const hookSrc = fs.readFileSync(path.resolve(__dirname, 'document-viewer/use-document-viewer-panel-state.ts'), 'utf8')
    const storeSrc = fs.readFileSync(path.resolve(__dirname, '../store/document-view.ts'), 'utf8')

    expect(shellSrc).toContain('aria-label="拖动调整文档查看器宽度"')
    expect(shellSrc).toContain('data-document-viewer-resize-handle="true"')
    expect(shellSrc).toContain('onPointerDown={handleResizePointerDown}')
    expect(shellSrc).toContain('style={panelStyle}')
    expect(hookSrc).toContain('panelWidthPx')
    expect(hookSrc).toContain('setPanelWidthPx')
    expect(storeSrc).toContain('panelWidthPx?: number')
  })
})
