from app.rag.preprocessing.cleaning import clean_markdown
from app.rag.preprocessing.rules import build_governance_rules


def test_governance_rule_pack_markdown_export_noise_removes_common_export_headers():
    text = "\n".join(
        [
            "Generated by Pandoc",
            "Exported from Notion",
            "Last updated on 2025-01-02",
            "Created with MkDocs",
            "",
            "# Title",
            "Real content stays.",
        ]
    )

    baseline = clean_markdown(
        text,
        rules=build_governance_rules([]),
        remove_toc_lines=False,
        remove_noise_lines=False,
        unwrap_lines=False,
        remove_common_lines=False,
        collapse_blank_lines=False,
    )
    assert "Pandoc" in baseline.markdown
    assert "Exported from Notion" in baseline.markdown

    packed = clean_markdown(
        text,
        rules=build_governance_rules([], rule_packs=["markdown_export_noise"]),
        remove_toc_lines=False,
        remove_noise_lines=False,
        unwrap_lines=False,
        remove_common_lines=False,
        collapse_blank_lines=False,
    )
    assert "Pandoc" not in packed.markdown
    assert "Exported from Notion" not in packed.markdown
    assert "Last updated" not in packed.markdown
    assert "Created with MkDocs" not in packed.markdown
    assert "# Title" in packed.markdown
    assert "Real content stays." in packed.markdown

