"""
Plain-text hierarchy chunking strategy.

Two-level hierarchy:
- paragraph nodes
- sentence nodes (children of paragraphs)

This is designed to work with the retrieval-time hierarchy overlay:
- hierarchy expansion (parent/sibling)
- family collapse + cross-query aggregation
- tree dedup (ancestor wins)

It intentionally does NOT attempt to build a full offline tree index.
"""


from langchain_core.documents import Document

from app.rag.chunking.base import BaseChunker
from app.rag.chunking.utils.hierarchical import hierarchical_chunk_markdown


class TextHierarchyChunker(BaseChunker):
    """
    Hierarchical chunker for plain text.

    Notes:
    - `chunk_size/chunk_overlap` are currently unused; splitting is structure-based
      (blank lines -> paragraphs, punctuation -> sentences).
    - We reuse the existing paragraph/sentence splitter used for Markdown preview,
      but override `chunk_strategy` + `hierarchy_basis` to keep metadata explicit.
    """

    def __init__(self, chunk_size: int, chunk_overlap: int):
        self.chunk_size = int(chunk_size or 0)
        self.chunk_overlap = int(chunk_overlap or 0)

    def split_documents(self, documents: list[Document]) -> list[Document]:
        out: list[Document] = []

        for doc in documents:
            text = doc.page_content or ""
            base_meta = dict(doc.metadata or {})
            if not text.strip():
                continue

            data = hierarchical_chunk_markdown(text) or {}
            paragraphs = data.get("paragraphs") if isinstance(data, dict) else None
            sentences = data.get("sentences") if isinstance(data, dict) else None
            paragraphs = paragraphs if isinstance(paragraphs, list) else []
            sentences = sentences if isinstance(sentences, list) else []

            # Group sentences by paragraph id for stable output order.
            sentences_by_parent: dict[str, list[dict]] = {}
            for s in sentences:
                if not isinstance(s, dict):
                    continue
                pid = str(s.get("parent_id") or "").strip()
                if not pid:
                    continue
                sentences_by_parent.setdefault(pid, []).append(s)

            for _pid, slist in sentences_by_parent.items():
                slist.sort(key=lambda x: int(x.get("index") or 0))

            for p in paragraphs:
                if not isinstance(p, dict):
                    continue
                p_text = str(p.get("text") or "")
                if not p_text.strip():
                    continue

                start = int(p.get("start") or 0)
                end = int(p.get("end") or (start + len(p_text)))
                pid = str(p.get("id") or p.get("hierarchy_node_key") or "").strip()
                if not pid:
                    continue

                p_meta = dict(base_meta)
                p_meta.update(
                    {
                        "chunk_strategy": "text_hierarchy",
                        "chunk_role": "paragraph",
                        "start_char": start,
                        "end_char": end,
                        "parent_id": pid,
                        # Preserve hierarchy keys generated by the splitter, but stamp a
                        # plain-text basis for easier debugging.
                        "hierarchy_basis": "text_hierarchy",
                        "hierarchy_level": p.get("hierarchy_level") or "paragraph",
                        "hierarchy_node_key": p.get("hierarchy_node_key") or pid,
                        "hierarchy_family_key": p.get("hierarchy_family_key") or pid,
                        "hierarchy_parent_key": None,
                        "hierarchy_prev_sibling_key": p.get("hierarchy_prev_sibling_key"),
                        "hierarchy_next_sibling_key": p.get("hierarchy_next_sibling_key"),
                        "hierarchy_sibling_index": p.get("hierarchy_sibling_index"),
                        "tokens_est": p.get("tokens_est"),
                    }
                )
                p_meta["chunk_index"] = len(out)
                out.append(Document(page_content=p_text, metadata=p_meta))

                for s in sentences_by_parent.get(pid, []):
                    s_text = str(s.get("text") or "")
                    if not s_text.strip():
                        continue
                    s_start = int(s.get("start") or start)
                    s_end = int(s.get("end") or (s_start + len(s_text)))

                    sid = str(s.get("id") or s.get("hierarchy_node_key") or "").strip()
                    if not sid:
                        continue

                    s_meta = dict(base_meta)
                    s_meta.update(
                        {
                            "chunk_strategy": "text_hierarchy",
                            "chunk_role": "sentence",
                            "start_char": s_start,
                            "end_char": s_end,
                            "parent_id": pid,
                            "hierarchy_basis": "text_hierarchy",
                            "hierarchy_level": s.get("hierarchy_level") or "sentence",
                            "hierarchy_node_key": s.get("hierarchy_node_key") or sid,
                            "hierarchy_family_key": s.get("hierarchy_family_key") or pid,
                            "hierarchy_parent_key": pid,
                            "hierarchy_prev_sibling_key": s.get("hierarchy_prev_sibling_key"),
                            "hierarchy_next_sibling_key": s.get("hierarchy_next_sibling_key"),
                            "hierarchy_sibling_index": s.get("hierarchy_sibling_index"),
                            "tokens_est": s.get("tokens_est"),
                        }
                    )
                    s_meta["chunk_index"] = len(out)
                    out.append(Document(page_content=s_text, metadata=s_meta))

        return out


__all__ = ["TextHierarchyChunker"]
