import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

describe('knowledge ingestion operation page client source', () => {
  it('renders an ingestion center aligned to the task-creation design with real upload actions', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'operation-page-client.tsx'), 'utf8')

    expect(src).toContain('入库中心')
    expect(src).toContain("import { useRouter, useSearchParams } from 'next/navigation'")
    expect(src).toContain('const searchParams = useSearchParams()')
    expect(src).toContain("const routeDatasetId = searchParams.get('datasetId') || ''")
    expect(src).toContain('const routeDatasetExists = routeDatasetId && datasets.some((dataset) => dataset.id === routeDatasetId)')
    expect(src).toContain("if (routeDatasetExists && current.datasetId !== routeDatasetId) return { ...current, datasetId: routeDatasetId }")
    expect(src).toContain("import { PageHeader } from '@/components/ui/page-header'")
    expect(src).toContain('<PageHeader')
    expect(src).toContain('iconImage="ingestion-operation"')
    expect(src).toContain('badge="INGESTION"')
    expect(src).toContain('<IngestionViewSwitch />')
    expect(src).not.toContain('<PageTitleIcon name="ingestion-operation"')
    expect(src).not.toContain('text-[1.55rem] font-semibold tracking-[-0.035em] text-slate-950')
    expect(src).not.toContain('选择数据去向与导入方式，监控入库进度，并保持数据集状态与知识库同步。')
    expect(src).toContain('目标数据集')
    expect(src).toContain('数据来源')
    expect(src).toContain('入库任务创建')
    expect(src).toContain('入库进度与任务列表')
    expect(src).toContain('已选文件')
    expect(src.match(/SOURCE_OPTIONS\.map/g)).toHaveLength(1)
    expect(src).not.toContain('导入来源')
    expect(src).not.toContain('样本预检')
    expect(src).not.toContain('本次入库任务')
    expect(src).not.toContain('待接入')
    expect(src).not.toContain('任务日志')
    expect(src).not.toContain('进入大屏')
    expect(src).not.toContain('人员和权限')
    expect(src).not.toContain('同步状态')
    expect(src).not.toContain('已选择数据集')
    expect(src).not.toContain('待提交来源')
    expect(src).not.toContain('后端处理中')
    expect(src).not.toContain('同步完成')
    expect(src).not.toContain('同步方式')
    expect(src).not.toContain('同步目标')
    expect(src).not.toContain('后端待处理')
    expect(src).not.toContain('最后处理')
    expect(src).not.toContain('目标数据集信息')
    expect(src).not.toContain('入库链路')
    expect(src).not.toContain('当前编排')
    expect(src).not.toContain('任务历史')
    expect(src).not.toContain('运行日志')
    expect(src).not.toContain('<aside className="space-y-4">')
    expect(src).toContain('flex min-h-full overflow-y-auto')
    expect(src).toContain('mx-auto flex min-h-[calc(100dvh-1.25rem)] w-full max-w-[1680px] flex-col gap-2')
    expect(src).toContain('<main className="flex min-h-0 flex-1 flex-col gap-2">')
    expect(src).not.toContain('<main className="space-y-2">')
    expect(src).toContain('px-4 py-2.5 text-foreground lg:px-5')
    expect(src).toContain('hsl(var(--primary)/0.08)')
    expect(src).toContain('hsl(var(--background))_0%')
    expect(src).toContain('WORKBENCH_SURFACE_CLASS')
    expect(src).toContain('StatusRail')
    expect(src).toContain('statusRailItems')
    expect(src).not.toContain('MetricCard')
    expect(src).not.toContain('grid gap-2 md:grid-cols-2 xl:grid-cols-4')
    expect(src).toContain('SOFT_PANEL_CLASS')
    expect(src).toContain('SOFT_CONTROL_CLASS')
    expect(src).toContain('rounded-[1.45rem]')
    expect(src).toContain('bg-card/78')
    expect(src).toContain('border-border/60')
    expect(src).toContain('border border-border/55 bg-background/42')
    expect(src).toContain('bg-info/[0.10] text-info ring-1 ring-info/20')
    expect(src).toContain('md:border-border/55')
    expect(src).toContain('hsl(var(--primary)/0.10)')
    expect(src).toContain('shadow-[0_0_0_4px_hsl(var(--primary)/0.14)]')
    expect(src).not.toContain('border border-blue-50 bg-blue-50/22')
    expect(src).not.toContain('bg-blue-50/80 text-blue-600 ring-1 ring-blue-100/80')
    expect(src).not.toContain('md:border-blue-100/70')
    expect(src).not.toContain('rgba(147,197,253,0.12)')
    expect(src).not.toContain('linear-gradient(180deg,#ffffff,#f7fbff)')
    expect(src).not.toContain('#fbfdff')
    expect(src).not.toContain('#f6faff')
    expect(src).not.toContain('#f9fbff')
    expect(src).not.toContain('border-l-[5px] border-slate-950')
    expect(src).not.toContain('border-blue-300 bg-blue-50/80 shadow-[0_10px_24px_rgba(37,99,235,0.1)]')
    expect(src).not.toContain('rounded-[1.1rem] border border-slate-200/82 bg-white/92')
    expect(src).not.toContain('min-h-[2.75rem]')
    expect(src).not.toContain('rounded-[1.08rem] border px-2 py-1.5 text-left transition')
    expect(src).toContain('min-h-[3.35rem]')
    expect(src).toContain('data-selected-files-table="stable"')
    expect(src).toContain('flex h-[10.75rem] flex-col')
    expect(src).toContain('[scrollbar-gutter:stable]')
    expect(src).toContain('table-fixed')
    expect(src).toContain('<colgroup>')
    expect(src).toContain('text-[1.02rem]')
    expect(src).toContain('if (!rows.length) return null')
    expect(src).toContain('capacitySummary')
    expect(src).toContain('当前目标数据集')
    expect(src).toContain('自动建索引')
    expect(src).toContain('IngestTaskControls')
    expect(src).toContain('<IngestTaskControls')
    expect(src).toContain('tagOptions={tagOptions}')
    expect(src).toContain('collectionOptions={collectionOptions}')
    expect(src.indexOf('<IngestTaskControls')).toBeLessThan(
      src.indexOf('<Select value={statusFilter}')
    )
    expect(src).toContain('mb-2 flex flex-wrap items-center justify-between gap-2')
    expect(src).toContain('className="flex min-w-0 flex-wrap items-center justify-end gap-1.5"')
    expect(src).not.toContain('rounded-[1.05rem] border border-blue-100/60 bg-blue-50/20 px-2.5 py-2')
    expect(src).not.toContain('flex min-w-0 flex-1 flex-wrap items-center justify-end gap-1.5')
    expect(src).toContain('border border-border/55 bg-background/50')
    expect(src).toContain('data-[state=checked]:bg-primary')
    expect(src).toContain('border border-border/60 bg-card/72')
    expect(src).toContain('bg-muted/38 text-muted-foreground')
    expect(src).toContain('font-mono text-primary')
    expect(src).toContain('bg-muted/70')
    expect(src).toContain('bg-primary')
    expect(src).not.toContain('border-blue-100/55 bg-blue-50/18')
    expect(src).not.toContain('data-[state=checked]:bg-blue-500')
    expect(src).not.toContain('data-[state=unchecked]:bg-slate-200')
    expect(src).not.toContain('border-blue-100/70 bg-white/74')
    expect(src).not.toContain('bg-blue-50/38 text-slate-500')
    expect(src).not.toContain('border border-blue-100/70 bg-white/82')
    expect(src).not.toContain('text-slate-700')
    expect(src).toContain("const [statusFilter, setStatusFilter] = useState<'all' | 'running' | 'done'>('all')")
    expect(src).toContain('const filteredTasks = useMemo(')
    expect(src).toContain('filteredTasks.slice(')
    expect(src).not.toContain('IngestMetadataBar')
    expect(src).not.toContain('<IngestMetadataBar draft={draft} updateDraft={updateDraft} />')
    expect(src).not.toContain('SummaryNumber')
    expect(src).not.toContain('label="文档数"')
    expect(src).not.toContain('label="分片数"')
    expect(src).not.toContain('label="存储占用"')
    expect(src).not.toContain('totalCharacters')
    expect(src).toContain('const TASK_LIST_PAGE_SIZE = 6')
    expect(src).toContain('paginatedTasks')
    expect(src).toContain('data-ingestion-task-list-card="true"')
    expect(src).toContain("flex min-h-[260px] flex-1 flex-col p-2.5")
    expect(src).toContain("cn(TABLE_SHELL_CLASS, 'min-h-0 flex-1 overflow-auto')")
    expect(src).toContain('第 {safePage} / {totalPages} 页')
    expect(src).toContain('mt-auto flex flex-wrap items-center justify-end gap-2 border-t border-border/50 pt-2')
    expect(src).not.toContain('mt-2 flex flex-wrap items-center justify-end gap-2 border-t border-border/50 pt-2')
    expect(src).toContain("setPage((current) => Math.max(1, current - 1))")
    expect(src).toContain("setPage((current) => Math.min(totalPages, current + 1))")
    expect(src).not.toContain('flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-1.5 py-1 text-xs text-slate-600')
    expect(src).not.toContain('px-5 py-4 text-foreground lg:px-7')
    expect(src).not.toContain('grid gap-4 md:grid-cols-2 xl:grid-cols-4')
    expect(src).not.toContain('min-h-[3.45rem]')
    expect(src).not.toContain('min-h-[4.6rem]')
    expect(src).not.toContain('max-h-[10rem]')
    expect(src).not.toContain('text-[1.35rem]')
    expect(src).not.toContain('待入库文件为空')
    expect(src).not.toContain('connectorRuns.slice(0, 5)')
    expect(src).not.toContain('documents.slice(0, 5)')
    expect(src).toContain('IngestionViewSwitch')
    expect(src).toContain("documentApi.uploadBatch(files")
    expect(src).toContain('documentApi.createFromChunks({')
    expect(src).toContain('connectorApi.createRun({')
    expect(src).toContain("connector_id: 'url_batch'")
    expect(src).toContain("connector_id: 'minio_bucket'")
    expect(src).toContain("folderInputRef.current?.setAttribute('webkitdirectory'")
    expect(src).not.toContain('new File([apiContent]')
    expect(src).toContain('settingsApi.get()')
    expect(src).toContain('url_ingest.enabled')
    expect(src).toContain('urlIngestEnabled')
    expect(src).toContain('URL 导入未启用')
    expect(src).not.toContain('生成临时文件')
    expect(src).toContain("uploadFiles(draft.executionMode === 'upload_only' ? 'upload_only' : 'ingest')")
    expect(src).not.toContain("precheck_only:")
    expect(src).not.toContain("uploadFiles('precheck')")
    expect(src).toContain('user_metadata_map')
  })

  it('scopes selected files, tag suggestions, and target folder suggestions to the active dataset', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'operation-page-client.tsx'), 'utf8')

    expect(src).toContain("const NO_DATASET_FILE_BUCKET = '__mimirq_no_dataset__'")
    expect(src).toContain('const [filesByDatasetId, setFilesByDatasetId] = useState<Record<string, File[]>>({})')
    expect(src).toContain('const activeFileBucketKey = draft.datasetId || NO_DATASET_FILE_BUCKET')
    expect(src).toContain('const files = filesByDatasetId[activeFileBucketKey] ?? []')
    expect(src).toContain('setFilesByDatasetId((current) => {')
    expect(src).toContain('[activeFileBucketKey]: Array.from(byKey.values())')
    expect(src).toContain('previousDatasetIdRef')
    expect(src).toContain('setUploadResponse(null)')
    expect(src).toContain('documentApi.folders({ dataset_id: draft.datasetId, max_depth: 20 })')
    expect(src).toContain('collectTagOptions(documents, draft.tags)')
    expect(src).toContain('collectCollectionOptions(foldersQuery.data?.root, files, draft.collection)')
    expect(src).toContain('list={tagListId}')
    expect(src).toContain('list={collectionListId}')
    expect(src).toContain('<datalist id={tagListId}>')
    expect(src).toContain('<datalist id={collectionListId}>')
    expect(src).toContain('fileUploadName(file)')
  })

  it('uses backend statistics instead of demo metrics or hardcoded dataset facts', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'operation-page-client.tsx'), 'utf8')

    expect(src).toContain('datasetApi.getIngestionStats')
    expect(src).toContain('ingestionStatsQuery')
    expect(src).toContain('total_size')
    expect(src).not.toContain('较昨日')
    expect(src).not.toContain('98.6')
    expect(src).not.toContain('documentCount * 84_000')
    expect(src).not.toContain('/ 产品资料 / 手册文档')
    expect(src).not.toContain('1536')
  })

  it('does not default ingestion to the full parse plus index pipeline', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'operation-page-client.tsx'), 'utf8')

    expect(src).toContain("type IngestExecutionMode = 'upload_only' | 'parse_only' | 'full_index'")
    expect(src).toContain("executionMode: 'upload_only'")
    expect(src).toContain('function isIngestExecutionMode(value: unknown): value is IngestExecutionMode')
    expect(src).toContain('function shouldBuildIndexes(draft: DraftState)')
    expect(src).toContain("return draft.executionMode === 'full_index'")
    expect(src).toContain('chunk_vector_enabled: shouldBuildIndexes(draft)')
    expect(src).toContain('bm25_index_enabled: shouldBuildIndexes(draft)')
    expect(src).toContain('执行阶段')
    expect(src).toContain('仅登记到知识库（不解析）')
    expect(src).toContain('入库并解析（不建索引）')
    expect(src).toContain('完整入库（解析 + 索引）')
    expect(src).not.toContain('仅预检（不解析入库）')
    expect(src).not.toContain('<SelectItem value="precheck">仅预检（不解析入库）</SelectItem>')
    expect(src).toContain("uploadFiles(draft.executionMode === 'upload_only' ? 'upload_only' : 'ingest')")
    expect(src).not.toContain("onClick={() => detachPromise(uploadFiles('precheck'))}")
    expect(src).not.toContain("precheck_only: mode === 'precheck'")
    expect(src).toContain("upload_only: mode === 'upload_only'")
    expect(src).toContain("function shouldOpenExecutionMonitor(draft: DraftState, mode: 'upload_only' | 'ingest')")
    expect(src).toContain("return mode === 'ingest' && draft.executionMode === 'parse_only'")
    expect(src).toContain("router.push('/knowledge/ingestion?mode=execution-monitor')")
    expect(src).toContain('登记到知识库')
    expect(src).not.toContain('chunk_vector_enabled: draft.autoSyncIndex')
    expect(src).not.toContain('bm25_index_enabled: draft.autoSyncIndex')
  })
})
