import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

describe('knowledge ingestion operation page client source', () => {
  it('renders an ingestion center aligned to the task-creation design with real upload actions', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'operation-page-client.tsx'), 'utf8')

    expect(src).toContain('入库中心')
    expect(src).toContain("import { PageHeader } from '@/components/ui/page-header'")
    expect(src).toContain('<PageHeader')
    expect(src).toContain('iconImage="ingestion-operation"')
    expect(src).toContain('badge="INGESTION"')
    expect(src).toContain('<IngestionViewSwitch />')
    expect(src).not.toContain('<PageTitleIcon name="ingestion-operation"')
    expect(src).not.toContain('text-[1.55rem] font-semibold tracking-[-0.035em] text-slate-950')
    expect(src).not.toContain('选择数据去向与导入方式，监控入库进度，并保持数据集状态与知识库同步。')
    expect(src).toContain('目标数据集')
    expect(src).toContain('数据来源')
    expect(src).toContain('入库任务创建')
    expect(src).toContain('入库进度与任务列表')
    expect(src).toContain('已选文件')
    expect(src.match(/SOURCE_OPTIONS\.map/g)).toHaveLength(1)
    expect(src).not.toContain('导入来源')
    expect(src).not.toContain('样本预检')
    expect(src).not.toContain('本次入库任务')
    expect(src).not.toContain('待接入')
    expect(src).not.toContain('任务日志')
    expect(src).not.toContain('进入大屏')
    expect(src).not.toContain('人员和权限')
    expect(src).not.toContain('同步状态')
    expect(src).not.toContain('已选择数据集')
    expect(src).not.toContain('待提交来源')
    expect(src).not.toContain('后端处理中')
    expect(src).not.toContain('同步完成')
    expect(src).not.toContain('同步方式')
    expect(src).not.toContain('同步目标')
    expect(src).not.toContain('后端待处理')
    expect(src).not.toContain('最后处理')
    expect(src).not.toContain('目标数据集信息')
    expect(src).not.toContain('入库链路')
    expect(src).not.toContain('当前编排')
    expect(src).not.toContain('任务历史')
    expect(src).not.toContain('运行日志')
    expect(src).not.toContain('<aside className="space-y-4">')
    expect(src).toContain('<main className="space-y-2">')
    expect(src).toContain('px-4 py-2.5 text-foreground lg:px-5')
    expect(src).toContain('WORKBENCH_SURFACE_CLASS')
    expect(src).toContain('StatusRail')
    expect(src).toContain('statusRailItems')
    expect(src).not.toContain('MetricCard')
    expect(src).not.toContain('grid gap-2 md:grid-cols-2 xl:grid-cols-4')
    expect(src).toContain('SOFT_PANEL_CLASS')
    expect(src).toContain('SOFT_CONTROL_CLASS')
    expect(src).toContain('rounded-[1.45rem]')
    expect(src).toContain('bg-white/82')
    expect(src).toContain('border-blue-100/70')
    expect(src).not.toContain('border-l-[5px] border-slate-950')
    expect(src).not.toContain('border-blue-300 bg-blue-50/80 shadow-[0_10px_24px_rgba(37,99,235,0.1)]')
    expect(src).not.toContain('rounded-[1.1rem] border border-slate-200/82 bg-white/92')
    expect(src).not.toContain('min-h-[2.75rem]')
    expect(src).not.toContain('rounded-[1.08rem] border px-2 py-1.5 text-left transition')
    expect(src).toContain('min-h-[3.35rem]')
    expect(src).toContain('max-h-[7.5rem]')
    expect(src).toContain('text-[1.02rem]')
    expect(src).toContain('if (!rows.length) return null')
    expect(src).toContain('capacitySummary')
    expect(src).toContain('当前目标数据集')
    expect(src).toContain('自动同步知识库')
    expect(src).toContain('IngestTaskControls')
    expect(src).toContain('<IngestTaskControls draft={draft} updateDraft={updateDraft} />')
    expect(src.indexOf('<IngestTaskControls draft={draft} updateDraft={updateDraft} />')).toBeLessThan(
      src.indexOf('<Select value={statusFilter}')
    )
    expect(src).toContain('mb-2 flex flex-wrap items-center justify-between gap-2')
    expect(src).toContain('className="flex min-w-0 flex-wrap items-center justify-end gap-1.5"')
    expect(src).not.toContain('rounded-[1.05rem] border border-blue-100/60 bg-blue-50/20 px-2.5 py-2')
    expect(src).not.toContain('flex min-w-0 flex-1 flex-wrap items-center justify-end gap-1.5')
    expect(src).toContain("const [statusFilter, setStatusFilter] = useState<'all' | 'running' | 'done'>('all')")
    expect(src).toContain('const filteredTasks = useMemo(')
    expect(src).toContain('filteredTasks.slice(')
    expect(src).not.toContain('IngestMetadataBar')
    expect(src).not.toContain('<IngestMetadataBar draft={draft} updateDraft={updateDraft} />')
    expect(src).not.toContain('SummaryNumber')
    expect(src).not.toContain('label="文档数"')
    expect(src).not.toContain('label="分片数"')
    expect(src).not.toContain('label="存储占用"')
    expect(src).not.toContain('totalCharacters')
    expect(src).toContain('const TASK_LIST_PAGE_SIZE = 6')
    expect(src).toContain('paginatedTasks')
    expect(src).toContain('第 {safePage} / {totalPages} 页')
    expect(src).toContain('mt-2 flex flex-wrap items-center justify-end gap-2 border-t border-blue-50 pt-2')
    expect(src).toContain("setPage((current) => Math.max(1, current - 1))")
    expect(src).toContain("setPage((current) => Math.min(totalPages, current + 1))")
    expect(src).not.toContain('flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-1.5 py-1 text-xs text-slate-600')
    expect(src).not.toContain('px-5 py-4 text-foreground lg:px-7')
    expect(src).not.toContain('grid gap-4 md:grid-cols-2 xl:grid-cols-4')
    expect(src).not.toContain('min-h-[3.45rem]')
    expect(src).not.toContain('min-h-[4.6rem]')
    expect(src).not.toContain('max-h-[10rem]')
    expect(src).not.toContain('text-[1.35rem]')
    expect(src).not.toContain('待入库文件为空')
    expect(src).not.toContain('connectorRuns.slice(0, 5)')
    expect(src).not.toContain('documents.slice(0, 5)')
    expect(src).toContain('IngestionViewSwitch')
    expect(src).toContain("documentApi.uploadBatch(files")
    expect(src).toContain('connectorApi.createRun({')
    expect(src).toContain("connector_id: 'url_batch'")
    expect(src).toContain("connector_id: 'minio_bucket'")
    expect(src).toContain("folderInputRef.current?.setAttribute('webkitdirectory'")
    expect(src).toContain('new File([apiContent]')
    expect(src).toContain("precheck_only: mode === 'precheck'")
    expect(src).toContain("onClick={() => void uploadFiles('ingest')}")
    expect(src).toContain('user_metadata_map')
  })

  it('uses backend statistics instead of demo metrics or hardcoded dataset facts', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'operation-page-client.tsx'), 'utf8')

    expect(src).toContain('datasetApi.getIngestionStats')
    expect(src).toContain('ingestionStatsQuery')
    expect(src).toContain('total_size')
    expect(src).not.toContain('较昨日')
    expect(src).not.toContain('98.6')
    expect(src).not.toContain('documentCount * 84_000')
    expect(src).not.toContain('/ 产品资料 / 手册文档')
    expect(src).not.toContain('1536')
  })
})
