import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  expectSourceNotToContain,
  expectSourceToContain,
} from '@/lib/source-test-utils'

describe('knowledge ingestion execution monitor chrome', () => {
  it('keeps the execution monitor focused on live runtime state', () => {
    const src = fs.readFileSync(
      path.resolve(__dirname, 'page-client.tsx'),
      'utf8'
    )

    expectSourceToContain(src, "const showSalesPolicyBadge = mode === 'sales-audit'")
    expectSourceToContain(src, "showSalesPolicyBadge ? (")
    expectSourceToContain(src, "mode === 'sales-audit' ? '入库预检工作台' : '执行监控'")
    expectSourceToContain(src, "label: '监控范围'")
    expectSourceToContain(src, 'const executionCharacterFootprint = useMemo(() => {')
    expectSourceToContain(src, "Number(document.total_characters || 0)")
    expectSourceToContain(src, "`${totalCharacters.toLocaleString('zh-CN')} 字符`")
    expectSourceToContain(src, '字数待统计')
    expectSourceToContain(src, '暂无字数')
    expectSourceToContain(src, 'function estimatePdfPageCountFromSignals')
    expectSourceToContain(src, 'Math.ceil(chars / 900)')
    expectSourceToContain(src, 'Math.ceil(size / (350 * 1024))')
    expectSourceToContain(src, "label: '处理模式'")
    expectSourceToContain(src, 'taskQueueSnapshot.enabled')
    expectSourceToContain(src, 'recentThroughputDetail')
    expectSourceToContain(src, '运行信息汇聚')
    expectSourceToContain(src, 'const executionPipelineState = useMemo(() => {')
    expectSourceToContain(src, "estimateLabel: taskQueueSnapshot?.enabled ? '队列联动' : '自动估算'")
    expectSourceToContain(src, 'stageIncludes(document, [')
    expectSourceToContain(src, 'progressOf(document)')
    expectSourceToContain(src, 'totalChunks')
    expectSourceToContain(src, 'statusLabel: parserStatus.label')
    expectSourceToContain(src, '{executionPipelineState.estimateLabel}')
    expectSourceToContain(src, '{card.statusLabel}')
    expectSourceToContain(src, 'style={{ width: `${card.progress}%` }}')
    expectSourceToContain(src, '批次数据画像')
    expectSourceToContain(src, '按 3/1000 抽代表样本，已出现的文件类型每类至少覆盖 1 个')
    expectSourceToContain(src, 'const executionBatchAnalysis = useMemo(() => {')
    expectSourceToContain(src, 'const batchProfileBarOption = useMemo<EChartsOption>')
    expectSourceToContain(src, 'const PRECHECK_SAMPLE_NUMERATOR = 3')
    expectSourceToContain(src, 'const PRECHECK_SAMPLE_DENOMINATOR = 1000')
    expectSourceToContain(src, 'const PRECHECK_SAMPLE_MAX = 2000')
    expectSourceToContain(src, 'Math.ceil((totalFiles * PRECHECK_SAMPLE_NUMERATOR) / PRECHECK_SAMPLE_DENOMINATOR)')
    expectSourceToContain(src, 'presentTypeCount')
    expectSourceToContain(src, '3/1000 抽样 · 覆盖')
    expectSourceToContain(src, '每类至少 1 个')
    expectSourceToContain(src, 'PDF 平均字数')
    expectSourceToContain(src, 'PDF 平均页数')
    expectSourceToContain(src, 'PDF 图片数')
    expectSourceToContain(src, '表格/结构块')
    expectSourceToContain(src, '优先使用后端 page_count，缺失时才按字数/体量估算')
    expectSourceToContain(src, '来自后端 image_count / elements 图片引用')
    expectSourceToContain(src, '图片、表格、页数与结构块均优先读取后端元数据和 elements，不再用扫描页代理。')
    expectSourceToContain(src, "hasEstimatedPdfPages ? '估算' : ''")
    expectSourceToContain(src, 'collectSalesAuditSampleFiles(salesAuditSamples)')
    expectSourceToContain(src, '来自最新预检扫描')
    expectSourceToContain(src, '来自后端文档统计')
    expectSourceToContain(src, 'getDocumentRuntimeStats(document)')
    expectSourceToContain(src, '预检样本')
    expectSourceToContain(src, "mode === 'execution-monitor' ? 'py-3 md:py-3.5' : 'py-0'")
    expectSourceToContain(src, 'const EXECUTION_TASK_PAGE_SIZE = 5')
    expectSourceToContain(src, 'const [executionTaskPage, setExecutionTaskPage] = useState(1)')
    expectSourceToContain(src, 'const executionTaskPageCount = useMemo(')
    expectSourceToContain(src, 'const visibleExecutionTaskRows = useMemo(')
    expectSourceToContain(src, 'visibleExecutionTaskRows.map((document) => {')
    expectSourceToContain(src, '共 {executionTaskRows.length} 条')
    expectSourceToContain(src, '上一页')
    expectSourceToContain(src, '第 {executionTaskPage} /')
    expectSourceToContain(src, '{executionTaskPageCount} 页')
    expectSourceToContain(src, '下一页')
    expectSourceToContain(src, '范围、处理模式与质量指标合并展示')
    expectSourceToContain(src, '已处理 {executionProcessedTotal} / {documents.length}')
    expectSourceToContain(src, '质量指标')
    expectSourceToContain(src, '近 5 分钟 / 当前窗口')
    expectSourceToContain(src, 'executionKpiCards.slice(0, 3).map((item) => {')
    expectSourceToContain(src, 'executionKpiCards.slice(3).map((item) => {')
    expectSourceToContain(src, "label: '当前吞吐'")
    expectSourceToContain(src, "label: '平均处理耗时'")
    expectSourceToContain(src, "label: 'OCR 使用率'")
    expectSourceToContain(src, "{ name: 'PDF 占比', max: 100 }")
    expectSourceToContain(src, "{ name: '页数压力', max: 100 }")
    expectSourceToContain(src, "{ name: '字数压力', max: 100 }")
    expectSourceToContain(src, "{ name: '体积压力', max: 100 }")
    expectSourceToContain(src, "{ name: '图片资源', max: 100 }")
    expectSourceToContain(src, "{ name: '耗时压力', max: 100 }")
    expectSourceToContain(src, "{ name: '失败重试', max: 100 }")
    expectSourceToContain(src, 'xl:grid-cols-2 2xl:grid-cols-[1.1fr_0.9fr_0.9fr]')
    expectSourceToContain(src, 'xl:col-span-2 2xl:col-span-1')
    expectSourceToContain(src, 'h-[13rem]')
    expectSourceToContain(src, "'relative overflow-hidden rounded-[1.45rem] border border-border/60 bg-background/86 p-3 shadow-[0_28px_72px_-46px_rgba(15,23,42,0.32)] md:p-3.5'")
    expectSourceNotToContain(src, "detail: '全部项目'")
    expectSourceNotToContain(src, "detail: '待确认清单'")
    expectSourceNotToContain(src, "detail: '近 5 min'")
    expectSourceNotToContain(src, '运行态总览')
    expectSourceNotToContain(src, '联动下方风险、流水线与日志')
    expectSourceNotToContain(src, '质量指标（实时）')
    expectSourceNotToContain(src, 'OCR 成本预警雷达')
    expectSourceNotToContain(src, '批次难度摸底')
    expectSourceNotToContain(src, '建议先解析样本')
    expectSourceNotToContain(src, '约 1% 快速摸底')
    expectSourceNotToContain(src, '下限摸底样本')
    expectSourceNotToContain(src, 'executionTopStripItems.map')
    expectSourceNotToContain(src, "'border-t border-border/35 pt-2.5'")
    expectSourceNotToContain(src, '上传并入库')
    expectSourceNotToContain(src, "mode === 'sales-audit' ? 'min-h-[3.4rem]' : 'min-h-[3.4rem]'")
    expectSourceNotToContain(src, "label: '运行时长'")
    expectSourceNotToContain(src, 'executionRuntimeLabel')
    expectSourceNotToContain(src, '2xl:grid-cols-8')
    expectSourceNotToContain(src, '<LiveVelocity')
    expectSourceNotToContain(src, "{ name: 'OCR 复杂度', max: 100 }")
    expectSourceNotToContain(src, "{ name: '格式规范度', max: 100 }")
  })
})
