import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

describe('data cleaner source style', () => {
  it('uses light semantic action surfaces for clean and LLM controls', () => {
    const src = fs.readFileSync(path.resolve(__dirname, 'data-cleaner.tsx'), 'utf8')

    expect(src).not.toContain('Button onClick={handleApply} disabled={isApplying} className="h-8 flex-1 gap-2 rounded-lg shadow-none"')
    expect(src).not.toContain("variant={llmEnabled ? 'default' : 'outline'}")
    expect(src).not.toContain('border-primary/25 bg-primary/10 text-primary')
    expect(src).toContain('const resetButtonClass =')
    expect(src).toContain('rounded-full border-primary/30 bg-primary/[0.12]')
    expect(src).toContain('shadow-[0_10px_24px_-18px_hsl(var(--primary)/0.45)]')
    expect(src).toContain('rounded-[1rem] border border-accent/18 bg-accent/[0.045]')
    expect(src).toContain('border-accent/28 bg-accent/[0.09] text-accent')
  })

  it('gives the cleaning config area a calmer workbench hierarchy', () => {
    const cleanerSrc = fs.readFileSync(path.resolve(__dirname, 'data-cleaner.tsx'), 'utf8')
    const profileSrc = fs.readFileSync(path.resolve(__dirname, '../governance-profile-selector.tsx'), 'utf8')
    const pipelineSrc = fs.readFileSync(path.resolve(__dirname, '../pipeline-options-panel.tsx'), 'utf8')

    expect(cleanerSrc).toContain('const configHeaderClass =')
    expect(cleanerSrc).toContain('rounded-[1.12rem] border border-border/36 bg-card/62')
    expect(cleanerSrc).toContain('const rulesPanelClass =')
    expect(cleanerSrc).toContain('rounded-[1.12rem] border border-border/38 bg-card/50')
    expect(cleanerSrc).toContain('const configFlowClass =')
    expect(cleanerSrc).toContain('const configFlowStepClass =')
    expect(cleanerSrc).toContain('const configFlowConnectorClass =')
    expect(cleanerSrc).toContain('const configSubpanelClass =')
    expect(cleanerSrc).toContain('const cleanerLabelClass =')
    expect(cleanerSrc).toContain('const cleanerCaptionClass =')
    expect(cleanerSrc).toContain('text-[15px] font-semibold leading-5')
    expect(cleanerSrc).toContain('aria-label="智能清洗流程"')
    expect(cleanerSrc).toContain('按顺序合并治理预设、脚本补丁和规则管线')
    expect(cleanerSrc).toContain('治理预设')
    expect(cleanerSrc).toContain('规则清洗')
    expect(cleanerSrc).toContain('结果预览')
    expect(cleanerSrc).not.toContain('const configStageNumberClass =')
    expect(cleanerSrc).not.toContain('Profile</div>')
    expect(cleanerSrc).not.toContain('Pipeline</div>')
    expect(profileSrc).toContain('const primaryActionClass =')
    expect(profileSrc).toContain('const actionRailClass =')
    expect(profileSrc).toContain('rounded-full border-primary/24 bg-primary/[0.09]')
    expect(pipelineSrc).toContain('const toggleCardClass =')
    expect(pipelineSrc).toContain('border border-primary/12 bg-primary/[0.035]')
    expect(pipelineSrc).toContain('const indexPresetCardClass =')
    expect(pipelineSrc).toContain('border border-info/12 bg-info/[0.035]')
    expect(pipelineSrc).not.toContain('text-muted-foreground italic')
    expect(pipelineSrc).toContain('text-[11px] leading-snug text-muted-foreground/75')
    expect(pipelineSrc).toContain('compact && "px-2.5 py-1.5 text-[10px]"')
  })

  it('keeps the smart cleaning configuration compact and non-repetitive', () => {
    const cleanerSrc = fs.readFileSync(path.resolve(__dirname, 'data-cleaner.tsx'), 'utf8')
    const pipelineSrc = fs.readFileSync(path.resolve(__dirname, '../pipeline-options-panel.tsx'), 'utf8')

    expect(cleanerSrc).toContain('const configShellClass =')
    expect(cleanerSrc).toContain('PipelineOptionsPanel compact={true} showJsonToolbar={true} showIndexingControls={false}')
    expect(cleanerSrc).toContain('预设与治理规则集中配置')
    expect(cleanerSrc).toContain('规则开关与 JSON 配置')
    expect(cleanerSrc).not.toContain('预设、管线与索引策略集中配置')
    expect(cleanerSrc).not.toContain('预设 / 管线 / 索引模式')
    expect(cleanerSrc).toContain('const llmPanelClass =')
    expect(cleanerSrc).toContain('const diffPanelClass =')
    expect(cleanerSrc).toContain('const emptyStateClass =')
    expect(cleanerSrc).toContain('执行清洗后查看规则命中、文本变化和统一 diff')
    expect(cleanerSrc).toContain('执行智能清洗后，如果规则命中或出现风险提示')
    expect(cleanerSrc).toContain('当前还没有生成可比较的清洗结果')
    expect(pipelineSrc).toContain('const pipelinePanelClass = cn(')
    expect(pipelineSrc).toContain('compact ? "space-y-2.5 font-sans" : "space-y-3.5 font-sans"')
    expect(pipelineSrc).toContain('flex min-h-9 items-center justify-between gap-2')
    expect(pipelineSrc).toContain('高级配置')
    expect(pipelineSrc).toContain('JSON 导入导出')
    expect(pipelineSrc).toContain('h-6 rounded-full border-border/34 bg-background/32')
  })
})
