{{- if and .Values.persistence.uploads.enabled (not .Values.persistence.uploads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mimirq.fullname" . }}-uploads
  labels:
    {{- include "mimirq.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.uploads.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size | quote }}
  {{- if .Values.persistence.uploads.storageClassName }}
  storageClassName: {{ .Values.persistence.uploads.storageClassName | quote }}
  {{- end }}
{{- end }}

