{{- if and .Values.api.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mimirq.fullname" . }}
  labels:
    {{- include "mimirq.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "mimirq.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout | quote }}
{{- end }}

